<script lang="ts">
  import AssemblyPaper from "../../AssemblyPaper.svelte";
</script>

<p>Clock, Clock, Clock, essa palavra apareceu bastante no último capítulo mas o que é o clock? Eu imagino que você durante esse percurso inteiro tenha percebido que as coisas estão ficando muito maiores, e mesmo a gente focando em pequenos pedaços, simplificando os esquemas, ainda sim, a escala se tornou muito grande, quando para termos 4 bytes de memória precisamos de 32 flip flops de 1 bit, que por si só já tem várias portas lógicas, transistores, além dos outros circuitos como multiplexadores, agora imagine como deve ser ordenar tudo isso dentro do processador do seu computador ou celular, que possui tecnológica muito mais avançada, e uma escala muito maior de tudo que a gente já viu até agora, como é possível organizar tudo direitinho de forma eficiente, sem virar bagunça?</p>

<p>É aí onde entra o clock, o trabalho dele é coordenar todo mundo, que nem numa marcha de carnaval, onde o baterista bate o tambor para coordenar o ritmo de todas as outras pessoas performando, mas da onde vem o clock, como ele é gerado, quem controla, como ele é medido? são tantas perguntas e tão poucas respostas.</p>

<p>Sem entrar na parte da geologia, porque eu entendo de computadores, mas não de pedras, sei apenas que não pode comer pedra, mas enfim, o clock base é produzido por um componente localizado na placa mãe do dispositivo, um componente que dentro dele há uma pedra de quartzo, que quando recebe uma voltagem vibra, e essa vibração é precisa e gera um pulso elétrico, esse pulso é o nosso clock base, e ele é medido em hertz, talvez você já tenha ouvido falar de hertz, mas caso não saiba, é uma unidade de medida que mede algo que se repete por segundo, por exemplo, joãozinho grita de dor em 2 hertz, ou seja, ele grita de dor duas vezes por segundo, um clock base de um computador pode chegar a 100 mhz, ou 100 megahertz. 1 megahertz são 1000 kilohertz, e 1 kilohertz é 1000 hertz, ou seja, o clock base de um computador pode oscilar até 100 milhões de vezes por segundo, isso é um fiozinho ligando e desligando nessa velocidade, e o mais impressionante, é que para a computação moderna, isso é considerado devagar demais! E você achando que o seu professor bota prazo curto nas atividades, mas é justamente por ser lento que dentro do processador do seu computador, há um pequeno mecanismo que multiplica o clock base para criar um clock de processador muito maior.</p>

<p>O clock do processador pode chegar até 5 gigahertz, às vezes até mais dependendo do quanto no futuro você está lendo isso, 1 gigahertz são 1000 megahertz, a forma como esse componente multiplicador de clock funciona internamente não é relevante para nós nesse curso já que é uma complexidade que não precisamos nos preocupar, apenas saiba que ele existe e que o clock do processador roda a valores bem altos, mas no que o clock influencia nossos outros componentes?</p>

<p>Primeiro temos que examinar quais componentes temos dentro do nosso processador afinal, processadores modernos possuem vários componentes altamente complexos para acelerar e diminuir o uso de energia do processador, todo tipo de firula chique, nosso processador é mais simples,  o coitado apenas faz os processos básicos que se espera de um computador, e tá tudo bem com isso, nem sempre dá para ser o melhor em tudo, mas, enfim, quais são esses componentes base?</p>

<p>Já que vamos ver todos esses componentes vamos ver também o fluxo de dados em um ciclo do nosso clock, isto é, o que acontece quando o clock fica positivo e depois cai para negativo, um único pulso, vamos começar com o nosso clock já negativo e ver o que acontece quando ele fica positivo.</p>

<p>O primeiro passo da cpu vai ser ir atrás de instruções para executar, essas instruções vão estar armazenadas na memória ram, e o processador dentro dele, vai ter um registrador, isto é, um conjunto de flip flops que armazenam uma informação, a diferença entre um registrador e a memória ram, é que nem a diferença entre uma uva e um cacho de uvas, a memória ram é como um cacho de uvas já o registrador é uma única uva, nesse caso vamos ter um registrador cujo trabalho é armazenar o endereço de memória onde vamos encontrar a próxima instrução de código à ser executada.</p>

<p>Esse registrador é chamado de program counter, ou contador de programa, já que ele literalmente está contando qual a linha de código que tem que ser processada pelo processador, após a instrução apontada pelo registrador do program counter ser carregada da RAM, ele é armazenado em outro registrador, o instruction register, ou registrador de instrução, pronto para ser computado, em seguida outro componente a unidade de controle vai acionar as entradas necessárias do circuito para que aquela instrução seja executada.</p>

<p>A unidade de controle é um componente vital para o processador, porém não existe uma forma exata de criar um, cada arquitetura de processador pode fazer de um jeito diferente, o que se mantém igual é o seu princípio de funcionamento, que nem a ULA que vimos anteriormente, a unidade de controle quando recebe uma entrada binária como 0010 vai mapear isso para um conjunto de fios específicos, por exemplo, se 0010 for a instrução de somar dois números, a unidade de controle vai ligar todas as entradas necessárias nos outros componentes para que os dados cheguem na ULA para realizar essa soma.</p>

<p>Mas como a ULA vai fazer uma soma sem saber quais números somar? Como funciona isso?</p>

<p>A verdade é que, no processador existem vários registradores, o número de registradores e suas funções exatas variam de arquitetura para arquitetura, mas, por exemplo, é comum existirem dois registradores de dados, o registrador A e o registrador B, eles vão armazenar valores, para que quando a unidade de controle acione a ULA para fazer uma soma, os dados desses dois registradores sejam passados como entrada para a operação.</p>

<p>Mas não só de matemática vive o processador, por exemplo, para executar uma operação como somar 2+3 o processador na verdade precisa executar 3 instruções, vamos ver:</p>

<AssemblyPaper code={"DefinirA 0010;\nDefinirB 0011;\nSomar A B;"} />

<p>Vamos examinar o que temos aqui, cada linha representa uma instrução, a primeira fala para a unidade de controle acionar as trilhas para os flip flops do registrador A para que o número 2 em binário, 0010, seja armazenado nesse registrador, em seguida passamos outra instrução, armazenar o valor de 3, 0011, no registrador B, e por fim, falamos para o processador que queremos somar A e B, e o resultado vai ser salvo em A, por conveniência, isso claro, da forma que o nossa unidade de controle foi configurada para funcionar na nossa arquitetura, outra arquitetura poderia forçar o programador a especificar em qual registrador o resultado deveria ser salvo. Vale lembrar que somente uma dessas instruções vai ser executada num pulso do clock.</p>

<p>Por fim, após executarmos nossa instrução, vamos somar +1 no valor do nosso program counter, para que ele agora aponte para a próxima instrução de código à ser executada, nesse momento o nosso clock vai para o estado negativo do pulso, onde o valor computado de todo esse processo é salvo nos flip flops dos registradores, assim ficando pronto para o próximo pulso positivo que vai puxar a instrução e processá-lá num ciclo infinito até a cpu ficar sem instruções para processar.</p>

<p>Por fim,  como pudemos ver, a velocidade do clock da cpu está diretamente relacionada na velocidade que nosso processador vai realizar operações lógicas, com a velocidade máxima desse clock sendo determinada pela velocidade maxima que os elétrons conseguem fluir pelos nossos componentes e transistores para conseguir efetuar até a mais lenta das operações durante um ciclo do clock, vimos também os princípios e componentes básicos envolvidos no processo de execução de instruções de código, vamos ver no próximo capítulo mais sobre essas instruções, mas vale lembrar que além de operações matemáticas e de armazenamento de dados em registradores e RAM, a cpu também apresenta instruções para efetuar operações sobre seu próprio funcionamento, afinal, o registrador do program counter ainda é um registrador como qualquer outro, o que permite o programador a instruir a cpu a adicionar mais 8 ao seu valor, fazendo a cpu pular 8 linhas de código para frente, mas vamos ver isso em mais detalhes no próximo capítulo.</p>


